spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 999655885367-0p1hg4bm30f1u4l6lc2ubaoo052ur2fk.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:codebreaker_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql

server:
  port: 18081
  servlet:
    context-path: /codebreaker